### ISSUE TITLE
Got exception StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by isaac-nugroho** [mifosio/lang#4]
I got exception on running demo server in generating RsaKeyPair, as follows:
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at io.mifos.core.lang.security.RsaKeyPairFactory.createKeyTimestampNow(RsaKeyPairFactory.java:64)
        at io.mifos.core.lang.security.RsaKeyPairFactory.createKeyPair(RsaKeyPairFactory.java:52)
        at io.mifos.anubis.repository.TenantAuthorizationDataRepository.createSignatureSet(TenantAuthorizationDataRepository.java:97)
        at io.mifos.anubis.controller.SignatureCreatorRestController.createSignatureSet(SignatureCreatorRestController.java:59)

```
I think the root cause is on generating timestamp in RsaKeyPairFactory.createKeyTimestampNow, as it does not check whether the returned string result contains ".".

I'm using ubuntu and open jdk 8:
uname -a
Linux ubuntu 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by myrle-krantz** [comment]
I can't reproduce this error on my machine, but I've added a guard around the indexOf code which should prevent a re-occurrence.
